### PR TITLE
Fix #416 - wallet crashes after adding account.

### LINKED ISSUE #416: Crash when creating new account
Node type: geth/eth
OS: linux mint
Network type: test
Mist version: 0.5.2

Ethereum Wallet crashes, when I go to menu -> accounts -> new account; after i repeated the new password and hit OK. 

attached you can find my log-files
[node.log.zip](https://github.com/ethereum/mist/files/187604/node.log.zip)

PS: it's my first use of this software, and the main window remains blank white after startup. only the menu bar is visible. is this normal?

### PR DESCRIPTION
**Pull request by hiddentao**
This replaces #437

### CODE REVIEW

File: modules/ipcCommunicator.js [hunk 1]
```diff
@@ -32,32 +34,38 @@ ipc.on('backendAction_closeApp', function() {
...
 ipc.on('backendAction_sendToOwner', function(e, error, value) {
-    var windowId = e.sender.getId();
+    var windowId = e.sender.getId(),
+        senderWindow = global.windows[windowId];
 
-    if(global.windows[windowId]) {
-        global.windows[windowId].owner.send('windowMessage', global.windows[windowId].type, error, value);
+    var mainWindow = global.mainWindow;
 
+    if (_.get(senderWindow, 'owner')) {
```
Comment (frozeman) [inline modules/ipcCommunicator.js]: Are you're `_.get()` exists in underscore?
Im fine using lodash if you think its a better fit, as long as it also supports the api of underscore

File: utils/underscore.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+  /**
+   * Get a deeply nested object property.
+   *
+   * @param {Object} obj The object.
+   * @param {String} path The path within the object to fetch.
+   * @param {*} fallbackValue The value to return if given path not found.
+   *
+   * @return {*} Returns value if found; otherwise the fallbackVAlue.
+   */
+  get: function(obj, path, fallbackValue) {
```
Comment (frozeman) [inline utils/underscore.js]: Ah i see you implemented it.... hm maybe its just better to use loads then...

Comment (hiddentao) [inline utils/underscore.js]: Like you said, it may break some other stuff (e.g. I had to alias a couple of lodash methods to ensure minimongo kept working). I think at some point we should definitely switch to lodash though I'm not yet familiar with enough of the codebase to say with certainty that it won't break something. Perhaps you have a better idea of this.

Comment (frozeman) [inline utils/underscore.js]: Yeah. the minimongo could break, which i rather don't want to try out... haha

**Comment by frozeman** [comment]
Thanks for the fix!
