### PR TITLE
Fixes #305 by adding one extra password verification step

### LINKED ISSUE #305: Please help! Can't succeed importing my presale wallet after many different tries.
Hey guys,

I started trying to import my presale wallet (.json file) on Windows 10 64 bit using Mist 0.5.1. After 
dragging the file and typing the password I got a window message saying “Importing…” and got stucked there for long minutes. No ‘wrong password’ messages!

Second try: Same Windows and Mist versions. Started Mist again and this time I got the same window message saying “Importing…” plus a spinning icon (indicating a kind of ‘processing”). No ‘wrong password’ messages either!

Third try: Linux Ubuntu 14.04 32 bit and Mist 0.5.1. I proceeded the same way as before and got the same results as the second try. No ‘wrong password’ messages either!

Fourth try: Windows 10 64 bit using command lines (DOS) and geth 1.3.5. I typed the following:

_geth.exe wallet import path/file.json_ and got **a very strange error message** as the attached picture:

12829364_10153921477536192_1746291932945441010_o

I am starting to get worried about this. Mainly because this is my second presale wallet and with the first presale wallet I just tried the first step reported above and worked fine!

Also tried to import my first presale wallet using Windows command line as fourth try and it succeeded. That worries me even more!

Please support me!

One more thing: my password contains $ character (as I read somewhere here in the issues).

Cheers

### PR DESCRIPTION
**Pull request by alexvandesande**
Fixes #305 by adding one extra password verification step

### CODE REVIEW

File: modules/ipcCommunicator.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ ipc.on('backendAction_importPresaleFile', function(e, path, pw) {
         if(data)
             console.log('Imported presale: ', data);
 
-        if(data.indexOf('Decryption failed:') !== -1) {
+        if(data.indexOf('Decryption failed:') !== -1 || data.indexOf('not equal to expected addr') !== -1) {
```
Comment (fjl) [inline modules/ipcCommunicator.js]: We'll introduce a special exit code for this in the future so you don't need to match log messages.
